markdown: redcarpet
highlighter: true
permalink: /posts/:title/
rdiscount:
  extensions: [smart]
name: David Chudzicki
url: www.davidchudzicki.com
description: David Chudzicki
github_user: dchudz
gravatar_url: https://secure.gravatar.com/avatar/63bcfcfcdf0fb75e508151e5fd944092
exclude: [src]
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
post_dirs: false